export const FUNCTION_ID_NAME_SEPARATOR = '&';

export const MAX_HISTORY_RECORDS = 7;

export const MAX_BYTES_ALLOWED_PER_HISTORY_RESPONSE = 5000 // 5kb

export const LANDING_PAGE_RANDOM_WORDS_ANIMATION_DURATION = 10
export const LANDING_PAGE_RANDOM_ANIMATION_CYCLE_BETWEEN_WORDS = 10000
